#!/usr/bin/env python3
"""
destiny1-mk — Capture Card Mode
M&K to virtual DS4 controller bridge. Video comes from your capture card (OBS).
chiaki-ng runs in the background for controller forwarding only.
No focus detection — inputs are always active while F3 capture is on.
Mouse button events are consumed (not passed to other apps) while captured.
"""

import json
import math
import queue
import sys
import threading
import time
import ctypes
from ctypes import wintypes
from collections import defaultdict
from pathlib import Path

# ── Dependency check ─────────────────────────────────────────────────────────

missing = []
try:
    import vgamepad as vg
except ImportError:
    missing.append("vgamepad")
try:
    from pynput import keyboard as pk
except ImportError:
    missing.append("pynput")

if missing:
    print(f"[ERROR] Missing packages. Run:  pip install {' '.join(missing)}")
    sys.exit(1)

try:
    import cv2
    import numpy as np
    _HAVE_CV2 = True
except ImportError:
    _HAVE_CV2 = False

# ── Mouse hook constants ──────────────────────────────────────────────────────

WH_MOUSE_LL     = 14
WM_MOUSEMOVE    = 0x0200
WM_LBUTTONDOWN  = 0x0201
WM_LBUTTONUP    = 0x0202
WM_RBUTTONDOWN  = 0x0204
WM_RBUTTONUP    = 0x0205
WM_MBUTTONDOWN  = 0x0207
WM_MBUTTONUP    = 0x0208
WM_XBUTTONDOWN  = 0x020B
WM_XBUTTONUP    = 0x020C
XBUTTON1        = 0x0001
XBUTTON2        = 0x0002
LLMHF_INJECTED  = 0x00000001  # Set on synthetic events generated by SetCursorPos

HOOKPROC = ctypes.WINFUNCTYPE(ctypes.c_long, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM)

class MSLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("pt_x",        ctypes.c_long),
        ("pt_y",        ctypes.c_long),
        ("mouseData",   wintypes.DWORD),
        ("flags",       wintypes.DWORD),
        ("time",        wintypes.DWORD),
        ("dwExtraInfo", ctypes.c_size_t),
    ]

# ── Config ───────────────────────────────────────────────────────────────────

CONFIG_FILE = Path(__file__).parent / "config.json"

_SENS_BASE_X = 25.0
_SENS_BASE_Y = 22.0

DEFAULT_CONFIG = {
    "sensitivity": {
        "x": 1.0,
        "y": 1.0,
        "acceleration": 1.0,
        "ads_multiplier": 0.4
    },
    "bindings": {
        "w":           "ls_up",
        "a":           "ls_left",
        "s":           "ls_down",
        "d":           "ls_right",
        "space":       "cross",
        "c":           "circle",
        "shift":       "l3",
        "r":           "square",
        "t":           "triangle",
        "q":           "r1",
        "e":           "r3",
        "g":           "l1",
        "f":           "r2",
        "left_click":  "r2",
        "right_click": "l2",
        "tab":         "touchpad",
        "esc":         "options",
        "1":           "dpad_up",
        "2":           "dpad_down",
        "3":           "dpad_left",
        "4":           "dpad_right"
    },
    "capture_toggle": "f3",
    "update_hz": 250,
    "frame_gen": False,
    "frame_gen_device": 0
}


def load_config() -> dict:
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            user = json.load(f)
        cfg = {
            "sensitivity": {**DEFAULT_CONFIG["sensitivity"], **user.get("sensitivity", {})},
            "bindings":    {**DEFAULT_CONFIG["bindings"],    **user.get("bindings", {})},
            "capture_toggle":  user.get("capture_toggle",  DEFAULT_CONFIG["capture_toggle"]),
            "update_hz":       user.get("update_hz",       DEFAULT_CONFIG["update_hz"]),
            "frame_gen":       user.get("frame_gen",       DEFAULT_CONFIG["frame_gen"]),
            "frame_gen_device": user.get("frame_gen_device", DEFAULT_CONFIG["frame_gen_device"]),
        }
        return cfg
    with open(CONFIG_FILE, "w") as f:
        json.dump(DEFAULT_CONFIG, f, indent=2)
    print("[INFO] Created config.json with default bindings.")
    return DEFAULT_CONFIG.copy()


# ── DS4 action table ──────────────────────────────────────────────────────────

BTN      = vg.DS4_BUTTONS
DPAD     = vg.DS4_DPAD_DIRECTIONS
SPEC_BTN = vg.DS4_SPECIAL_BUTTONS

class RECT(ctypes.Structure):
    _fields_ = [("left", ctypes.c_long), ("top", ctypes.c_long),
                ("right", ctypes.c_long), ("bottom", ctypes.c_long)]

class POINT(ctypes.Structure):
    _fields_ = [("x", ctypes.c_long), ("y", ctypes.c_long)]

ACTION_BTN = {
    "cross":    BTN.DS4_BUTTON_CROSS,
    "circle":   BTN.DS4_BUTTON_CIRCLE,
    "square":   BTN.DS4_BUTTON_SQUARE,
    "triangle": BTN.DS4_BUTTON_TRIANGLE,
    "l1":       BTN.DS4_BUTTON_SHOULDER_LEFT,
    "r1":       BTN.DS4_BUTTON_SHOULDER_RIGHT,
    "l3":       BTN.DS4_BUTTON_THUMB_LEFT,
    "r3":       BTN.DS4_BUTTON_THUMB_RIGHT,
    "options":  BTN.DS4_BUTTON_OPTIONS,
    "share":    BTN.DS4_BUTTON_SHARE,
}

# ── Bridge ────────────────────────────────────────────────────────────────────

class InputBridge:
    def __init__(self, cfg: dict):
        self.cfg      = cfg
        self.bindings = cfg["bindings"]
        self.capture_toggle = cfg["capture_toggle"]

        sx = cfg["sensitivity"]
        self.sens_x   = _SENS_BASE_X / max(sx["x"], 0.001)
        self.sens_y   = _SENS_BASE_Y / max(sx["y"], 0.001)
        self.accel    = sx["acceleration"]
        self.ads_mult = sx["ads_multiplier"]
        self.dt       = 1.0 / cfg["update_hz"]

        self.pad      = vg.VDS4Gamepad()
        self.captured = False
        self.running  = False
        self._frame_gen        = cfg.get("frame_gen", False)
        self._frame_gen_device = cfg.get("frame_gen_device", 0)

        self._lock         = threading.Lock()
        self._action_count: dict[str, int] = defaultdict(int)
        self._held_keys:    set[str]        = set()
        self._mouse_dx     = 0.0
        self._mouse_dy     = 0.0
        self._hook_proc_ref = None  # Prevents garbage collection of the hook callback

        u32      = ctypes.windll.user32
        self._cx = u32.GetSystemMetrics(0) // 2
        self._cy = u32.GetSystemMetrics(1) // 2

    # ── Input normalisation ───────────────────────────────────────────────

    @staticmethod
    def _norm_key(key) -> str:
        try:
            if key.char:
                return key.char.lower()
        except AttributeError:
            pass
        try:
            n = key.name.lower()
            for suffix in ("_l", "_r"):
                if n.endswith(suffix):
                    return n[:-2]
            return n
        except AttributeError:
            return ""

    # ── pynput keyboard callbacks ─────────────────────────────────────────

    def _on_key_press(self, key):
        name = self._norm_key(key)
        with self._lock:
            if name in self._held_keys:
                return
            self._held_keys.add(name)
        if name == self.capture_toggle:
            self._toggle_capture()
            return
        if not self.captured:
            return
        self._input_down(name)

    def _on_key_release(self, key):
        name = self._norm_key(key)
        with self._lock:
            self._held_keys.discard(name)
        self._input_up(name)

    # ── Low-level mouse hook ──────────────────────────────────────────────

    def _run_mouse_hook(self):
        """
        Install a WH_MOUSE_LL hook. While captured, button events are consumed
        (return 1) so they never reach OBS or any other app. Movement is always
        passed through — cursor position is polled separately in _update().
        """
        u32 = ctypes.windll.user32

        def hook_proc(nCode, wParam, lParam):
            if nCode >= 0 and self.captured:
                info = ctypes.cast(lParam, ctypes.POINTER(MSLLHOOKSTRUCT)).contents

                if wParam == WM_MOUSEMOVE:
                    # Skip synthetic events generated by our own SetCursorPos calls
                    if not (info.flags & LLMHF_INJECTED):
                        with self._lock:
                            self._mouse_dx += info.pt_x - self._cx
                            self._mouse_dy += info.pt_y - self._cy
                        u32.SetCursorPos(self._cx, self._cy)
                    return 1  # Suppress — cursor stays locked at center

                if wParam == WM_LBUTTONDOWN:
                    self._input_down("left_click")
                    return 1
                elif wParam == WM_LBUTTONUP:
                    self._input_up("left_click")
                    return 1
                elif wParam == WM_RBUTTONDOWN:
                    self._input_down("right_click")
                    return 1
                elif wParam == WM_RBUTTONUP:
                    self._input_up("right_click")
                    return 1
                elif wParam == WM_MBUTTONDOWN:
                    self._input_down("middle_click")
                elif wParam == WM_MBUTTONUP:
                    self._input_up("middle_click")
                elif wParam == WM_XBUTTONDOWN:
                    xbtn = (info.mouseData >> 16) & 0xFFFF
                    self._input_down("mouse4" if xbtn == XBUTTON1 else "mouse5")
                elif wParam == WM_XBUTTONUP:
                    xbtn = (info.mouseData >> 16) & 0xFFFF
                    self._input_up("mouse4" if xbtn == XBUTTON1 else "mouse5")

            return u32.CallNextHookEx(None, nCode, wParam, lParam)

        self._hook_proc_ref = HOOKPROC(hook_proc)

        u32.SetWindowsHookExW.restype  = ctypes.c_void_p
        u32.SetWindowsHookExW.argtypes = [ctypes.c_int, HOOKPROC, wintypes.HINSTANCE, wintypes.DWORD]
        u32.CallNextHookEx.restype     = ctypes.c_long
        u32.CallNextHookEx.argtypes    = [ctypes.c_void_p, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM]
        u32.UnhookWindowsHookEx.restype  = wintypes.BOOL
        u32.UnhookWindowsHookEx.argtypes = [ctypes.c_void_p]

        hook = u32.SetWindowsHookExW(WH_MOUSE_LL, self._hook_proc_ref, None, 0)

        msg = wintypes.MSG()
        while self.running:
            ret = u32.PeekMessageW(ctypes.byref(msg), None, 0, 0, 1)
            if ret:
                u32.TranslateMessage(ctypes.byref(msg))
                u32.DispatchMessageW(ctypes.byref(msg))
            else:
                time.sleep(0.001)

        u32.UnhookWindowsHookEx(hook)

    # ── Action dispatch ───────────────────────────────────────────────────

    def _input_down(self, key_name: str):
        binding = self.bindings.get(key_name)
        if not binding:
            return
        actions = binding if isinstance(binding, list) else [binding]
        for action in actions:
            with self._lock:
                self._action_count[action] += 1
                first = self._action_count[action] == 1
            if first:
                self._press(action)

    def _input_up(self, key_name: str):
        binding = self.bindings.get(key_name)
        if not binding:
            return
        actions = binding if isinstance(binding, list) else [binding]
        for action in actions:
            with self._lock:
                self._action_count[action] = max(0, self._action_count[action] - 1)
                last = self._action_count[action] == 0
            if last:
                self._release(action)

    def _press(self, action: str):
        try:
            if action in ACTION_BTN:
                self.pad.press_button(ACTION_BTN[action])
            elif action == "touchpad":
                self.pad.press_special_button(SPEC_BTN.DS4_SPECIAL_BUTTON_TOUCHPAD)
            elif action == "l2":
                self.pad.left_trigger(value=255)
            elif action == "r2":
                self.pad.right_trigger(value=255)
            else:
                return
            self.pad.update()
        except Exception:
            pass

    def _release(self, action: str):
        try:
            if action in ACTION_BTN:
                self.pad.release_button(ACTION_BTN[action])
            elif action == "touchpad":
                self.pad.release_special_button(SPEC_BTN.DS4_SPECIAL_BUTTON_TOUCHPAD)
            elif action == "l2":
                self.pad.left_trigger(value=0)
            elif action == "r2":
                self.pad.right_trigger(value=0)
            else:
                return
            self.pad.update()
        except Exception:
            pass

    def _release_all(self):
        with self._lock:
            held = {a for a, c in self._action_count.items() if c > 0}
            self._action_count.clear()
            self._held_keys.clear()
        for action in held:
            self._release(action)

    # ── Analog update loop ────────────────────────────────────────────────

    def _update(self):
        with self._lock:
            ac = dict(self._action_count)

        # Left stick (WASD)
        lx = float(ac.get("ls_right", 0) > 0) - float(ac.get("ls_left",  0) > 0)
        ly = float(ac.get("ls_down",  0) > 0) - float(ac.get("ls_up",    0) > 0)
        mag = math.sqrt(lx * lx + ly * ly)
        if mag > 1.0:
            lx /= mag
            ly /= mag

        # Right stick — drain delta accumulated by the hook on every WM_MOUSEMOVE
        if self.captured:
            with self._lock:
                dx = self._mouse_dx
                dy = self._mouse_dy
                self._mouse_dx = 0.0
                self._mouse_dy = 0.0
            ads  = ac.get("l2", 0) > 0
            mult = self.ads_mult if ads else 1.0
            rx   = self._curve(dx, self.sens_x * mult)
            ry   = self._curve(dy, self.sens_y * mult)
        else:
            rx = ry = 0.0

        # D-pad
        up    = ac.get("dpad_up",    0) > 0
        down  = ac.get("dpad_down",  0) > 0
        left  = ac.get("dpad_left",  0) > 0
        right = ac.get("dpad_right", 0) > 0
        if   up and right:   dpad = DPAD.DS4_BUTTON_DPAD_NORTHEAST
        elif down and right: dpad = DPAD.DS4_BUTTON_DPAD_SOUTHEAST
        elif down and left:  dpad = DPAD.DS4_BUTTON_DPAD_SOUTHWEST
        elif up and left:    dpad = DPAD.DS4_BUTTON_DPAD_NORTHWEST
        elif up:             dpad = DPAD.DS4_BUTTON_DPAD_NORTH
        elif right:          dpad = DPAD.DS4_BUTTON_DPAD_EAST
        elif down:           dpad = DPAD.DS4_BUTTON_DPAD_SOUTH
        elif left:           dpad = DPAD.DS4_BUTTON_DPAD_WEST
        else:                dpad = DPAD.DS4_BUTTON_DPAD_NONE

        try:
            self.pad.left_joystick_float(x_value_float=lx, y_value_float=ly)
            self.pad.right_joystick_float(x_value_float=rx, y_value_float=ry)
            self.pad.directional_pad(direction=dpad)
            self.pad.update()
        except Exception:
            pass

    def _run_update_loop(self):
        while self.running:
            t0    = time.monotonic()
            self._update()
            sleep = self.dt - (time.monotonic() - t0)
            if sleep > 0:
                time.sleep(sleep)

    def _curve(self, delta: float, sensitivity: float) -> float:
        val  = delta / max(sensitivity, 0.001)
        sign = 1.0 if val >= 0.0 else -1.0
        return max(-1.0, min(1.0, sign * (abs(val) ** (1.0 / max(self.accel, 0.1)))))

    # ── Cursor visibility ─────────────────────────────────────────────────

    @staticmethod
    def _set_cursor_visible(visible: bool):
        u32 = ctypes.windll.user32
        if visible:
            while u32.ShowCursor(True) < 0:
                pass
        else:
            while u32.ShowCursor(False) >= 0:
                pass

    # ── Capture toggle ────────────────────────────────────────────────────

    def _toggle_capture(self):
        self.captured = not self.captured
        self._set_cursor_visible(not self.captured)
        if self.captured:
            hwnd = ctypes.windll.user32.GetForegroundWindow()
            rect = RECT()
            ctypes.windll.user32.GetWindowRect(hwnd, ctypes.byref(rect))
            self._cx = (rect.left + rect.right) // 2
            self._cy = (rect.top + rect.bottom) // 2
            with self._lock:
                self._mouse_dx = 0.0
                self._mouse_dy = 0.0
            ctypes.windll.user32.SetCursorPos(self._cx, self._cy)
            ctypes.windll.user32.ClipCursor(ctypes.byref(rect))
            print(f"[+] Mouse captured — inputs active  ({self.capture_toggle.upper()} to release)")
        else:
            self._release_all()
            with self._lock:
                self._mouse_dx = 0.0
                self._mouse_dy = 0.0
            ctypes.windll.user32.ClipCursor(None)
            print(f"[-] Mouse released — inputs paused  ({self.capture_toggle.upper()} to capture)")

    # ── Entry point ───────────────────────────────────────────────────────

    def start(self):
        self.running = True
        print("=" * 55)
        print("  destiny1-mk  |  Capture Card Mode")
        print("=" * 55)
        print(f"  Capture toggle : {self.capture_toggle.upper()}")
        sx = self.cfg["sensitivity"]
        print(f"  Sensitivity    : x={sx['x']}  y={sx['y']}")
        print(f"  Update rate    : {self.cfg['update_hz']} Hz")
        if self._frame_gen:
            if _HAVE_CV2:
                print(f"  Frame gen      : ON  (device {self._frame_gen_device}, 30→60 fps)")
            else:
                print("  Frame gen      : OFF (requires: pip install opencv-python)")
        else:
            print("  Frame gen      : OFF")
        print("  Edit config.json to change bindings/sensitivity")
        print("=" * 55)
        print()
        if self._frame_gen and _HAVE_CV2:
            print("  VIDEO  : Capture card feed shown in the Frame Gen window")
        else:
            print("  VIDEO  : Watch your game in OBS (capture card feed)")
        print("  INPUT  : chiaki-ng must be running on a virtual desktop")
        print()
        print("  Press F3 anywhere to capture mouse and start playing.")
        print("  Press F3 again to release. Ctrl+C to quit.")
        print()

        kb = pk.Listener(on_press=self._on_key_press, on_release=self._on_key_release)
        mouse_thread = threading.Thread(target=self._run_mouse_hook, daemon=True)
        kb.start()
        mouse_thread.start()

        fg = None
        if self._frame_gen and _HAVE_CV2:
            threading.Thread(target=self._run_update_loop, daemon=True).start()
            fg = FrameGenProcessor(self._frame_gen_device)
            fg.start()

        try:
            if fg is not None:
                fg.run_display_loop(self)
            else:
                while self.running:
                    t0    = time.monotonic()
                    self._update()
                    sleep = self.dt - (time.monotonic() - t0)
                    if sleep > 0:
                        time.sleep(sleep)
        finally:
            self.running = False
            if fg is not None:
                fg.stop()
            ctypes.windll.user32.ClipCursor(None)
            self._set_cursor_visible(True)
            kb.stop()


# ── Frame Generation ──────────────────────────────────────────────────────────

class FrameGenProcessor:
    """
    Captures video from a capture card device and uses optical flow to insert
    one interpolated frame between each real frame, doubling 30 fps to 60 fps.

    Pipeline:  _capture_loop → _raw_q → _interp_loop → _disp_q → run_display_loop
    """

    WINDOW = "destiny1 | Capture Card (60 fps)"

    def __init__(self, device: int):
        self._device  = device
        self._raw_q   = queue.Queue(maxsize=2)
        self._disp_q  = queue.Queue(maxsize=2)
        self._running = False

    def start(self):
        self._running = True
        threading.Thread(target=self._capture_loop, daemon=True).start()
        threading.Thread(target=self._interp_loop,  daemon=True).start()

    def stop(self):
        self._running = False

    # ── Capture thread ────────────────────────────────────────────────────

    def _capture_loop(self):
        cap = cv2.VideoCapture(self._device, cv2.CAP_DSHOW)
        if not cap.isOpened():
            print(f"[WARN] Frame gen: cannot open capture device {self._device}")
            return
        cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
        while self._running:
            ret, frame = cap.read()
            if not ret:
                time.sleep(0.005)
                continue
            if self._raw_q.full():
                try:
                    self._raw_q.get_nowait()
                except queue.Empty:
                    pass
            try:
                self._raw_q.put_nowait(frame)
            except queue.Full:
                pass
        cap.release()

    # ── Interpolation thread ──────────────────────────────────────────────

    def _interp_loop(self):
        # Track the last *unique* frame so that duplicate frames emitted by the
        # capture card (one real 30 fps frame sent twice to fill its 60 fps
        # output) are ignored. Interpolation only runs between two genuinely
        # different frames.
        prev_unique = None
        while self._running:
            try:
                curr = self._raw_q.get(timeout=0.1)
            except queue.Empty:
                continue
            if prev_unique is not None and self._is_duplicate(prev_unique, curr):
                continue
            if prev_unique is not None:
                interp = self._interpolate(prev_unique, curr)
                if self._disp_q.full():
                    try:
                        self._disp_q.get_nowait()
                    except queue.Empty:
                        pass
                try:
                    self._disp_q.put_nowait((interp, curr))
                except queue.Full:
                    pass
            prev_unique = curr

    def _is_duplicate(self, a: "np.ndarray", b: "np.ndarray") -> bool:
        # Downsample to a tiny thumbnail for a fast per-pixel comparison.
        # Capture card compression means true duplicates aren't bitwise identical,
        # but their MAD will be well below 3; genuine new frames will be much higher.
        small_a = cv2.resize(a, (64, 36))
        small_b = cv2.resize(b, (64, 36))
        return float(np.mean(np.abs(small_a.astype(np.int16) - small_b.astype(np.int16)))) < 3.0

    def _interpolate(self, prev: "np.ndarray", curr: "np.ndarray") -> "np.ndarray":
        h, w = prev.shape[:2]
        # Compute optical flow at half resolution for real-time performance
        hw, hh = w // 2, h // 2
        g_p = cv2.cvtColor(cv2.resize(prev, (hw, hh)), cv2.COLOR_BGR2GRAY)
        g_c = cv2.cvtColor(cv2.resize(curr, (hw, hh)), cv2.COLOR_BGR2GRAY)
        flow = cv2.calcOpticalFlowFarneback(g_p, g_c, None, 0.5, 2, 12, 2, 5, 1.1, 0)
        # Scale flow back to full resolution
        flow = cv2.resize(flow, (w, h)) * 2.0
        gy, gx = np.mgrid[0:h, 0:w].astype(np.float32)
        half = flow * 0.5
        # Bidirectional warp + blend for fewer artifacts
        wf = cv2.remap(prev, gx + half[..., 0], gy + half[..., 1], cv2.INTER_LINEAR)
        wb = cv2.remap(curr, gx - half[..., 0], gy - half[..., 1], cv2.INTER_LINEAR)
        return cv2.addWeighted(wf, 0.5, wb, 0.5, 0)

    # ── Display loop (main thread) ────────────────────────────────────────

    def run_display_loop(self, bridge: "InputBridge"):
        HALF = 1.0 / 60.0
        cv2.namedWindow(self.WINDOW, cv2.WINDOW_NORMAL)
        while bridge.running:
            try:
                interp, curr = self._disp_q.get(timeout=0.05)
            except queue.Empty:
                cv2.waitKey(1)
                continue
            cv2.imshow(self.WINDOW, interp)
            cv2.waitKey(1)
            time.sleep(max(0, HALF - 0.003))
            cv2.imshow(self.WINDOW, curr)
            cv2.waitKey(1)
        cv2.destroyAllWindows()


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    cfg = load_config()
    InputBridge(cfg).start()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[INFO] Exited.")
